export type ReservationLanguage = "en" | "pt";

const reservationCopy = {
  en: {
    reserveNow: "Reserve now",
    heroTitle: "Your coastal escape",
    heroSubtitle: "Mangal Beach Lodge",
    title: "Reserve your stay",
    subtitle: "Request availability based on the information below.",
    close: "Close reservation form",
    stayDetails: "Stay details",
    contactDetails: "Contact details",
    checkIn: "Check-in",
    checkInPlaceholder: "Select check-in",
    checkOut: "Check-out",
    checkOutPlaceholder: "Select check-out",
    adults: "Adults",
    children: "Children",
    fullName: "Full name",
    email: "Email address",
    phone: "Phone number",
    observation: "Notes or special requests",
    observationPlaceholder:
      "Tell us anything that will help us prepare your stay",
    staySummary: "Stay summary",
    breakfastIncluded: "Breakfast included",
    rooms: "Rooms",
    addRoom: "Add room",
    room: "Room",
    remove: "Remove",
    extraAdults: "Extra adults",
    extraChildren: "Extra children",
    extraAdultsPrice: "2,500 MZN per adult",
    extraChildrenPrice: "1,500 MZN per child",
    capacityWarning:
      "Capacity is {totalCapacity} guests, but you selected {guestCount}. Add another room.",
    capacityInfo: "Total capacity",
    guests: "guests",
    summary: "Price estimate",
    guestsLabel: "Guests",
    nights: "Nights",
    nightlyTotal: "Nightly total",
    totalStay: "Estimated stay",
    requestSent: "Request sent successfully. We’ll get back to you shortly.",
    sending: "Sending request…",
    submit: "Send availability request",
    adultsSummary: "adults",
    childrenSummary: "children",
    perNight: "per night",
    requiredHint: "All fields marked with * are required.",
    missingDates: "Please select valid check-in and check-out dates.",
    requestFailed: "We couldn’t send your request. Please try again.",
    recommendationStandard: "A Standard Room fits this request best.",
    recommendationVilla: "A Villa is the better fit for this guest count.",
    recommendationMultiple: "This group will likely need more than one room.",
    roomStandardLabel: "Standard Room",
    roomStandardDescription: "Double bed · breakfast included",
    roomStandardLayout: "Sleeps 2",
    roomVillaLabel: "Villa",
    roomVillaDescription:
      "Two-bedroom house · self catering · breakfast available on request",
    roomVillaLayout: "Sleeps 6 · 4 in rooms + 2 in a bunk near the common area",
  },
  pt: {
    reserveNow: "Reservar agora",
    heroTitle: "A sua escapadinha costeira",
    heroSubtitle: "Mangal Beach Lodge",
    title: "Reserve a sua estadia",
    subtitle: "Solicite disponibilidade com base nas informações abaixo.",
    close: "Fechar formulário de reserva",
    stayDetails: "Detalhes da estadia",
    contactDetails: "Dados de contacto",
    checkIn: "Check-in",
    checkInPlaceholder: "Selecione o check-in",
    checkOut: "Check-out",
    checkOutPlaceholder: "Selecione o check-out",
    adults: "Adultos",
    children: "Crianças",
    fullName: "Nome completo",
    email: "Endereço de email",
    phone: "Número de telefone",
    observation: "Observações ou pedidos especiais",
    observationPlaceholder:
      "Partilhe algo que nos ajude a preparar a sua estadia",
    staySummary: "Resumo da estadia",
    breakfastIncluded: "Pequeno-almoço incluído",
    rooms: "Quartos",
    addRoom: "Adicionar quarto",
    room: "Quarto",
    remove: "Remover",
    extraAdults: "Adultos extra",
    extraChildren: "Crianças extra",
    extraAdultsPrice: "2.500 MZN por adulto",
    extraChildrenPrice: "1.500 MZN por criança",
    capacityWarning:
      "A capacidade é de {totalCapacity} hóspedes, mas selecionou {guestCount}. Adicione outro quarto.",
    capacityInfo: "Capacidade total",
    guests: "hóspedes",
    summary: "Estimativa de preço",
    guestsLabel: "Hóspedes",
    nights: "Noites",
    nightlyTotal: "Total por noite",
    totalStay: "Estadia estimada",
    requestSent: "Pedido enviado com sucesso. Entraremos em contacto em breve.",
    sending: "A enviar pedido…",
    submit: "Enviar pedido de disponibilidade",
    adultsSummary: "adultos",
    childrenSummary: "crianças",
    perNight: "por noite",
    requiredHint: "Todos os campos assinalados com * são obrigatórios.",
    missingDates: "Selecione datas válidas de check-in e check-out.",
    requestFailed: "Não foi possível enviar o pedido. Tente novamente.",
    recommendationStandard: "Um Quarto Standard é ideal para este pedido.",
    recommendationVilla:
      "Uma Villa é mais indicada para este número de hóspedes.",
    recommendationMultiple:
      "Este grupo provavelmente precisará de mais de um quarto.",
    roomStandardLabel: "Quarto Standard",
    roomStandardDescription: "Cama de casal · pequeno-almoço incluído",
    roomStandardLayout: "Acomoda 2",
    roomVillaLabel: "Villa",
    roomVillaDescription:
      "Casa de dois quartos · self catering · pequeno-almoço disponível mediante pedido",
    roomVillaLayout:
      "Acomoda 6 · 4 nos quartos + 2 em beliche junto à área comum",
  },
} as const;

export type ReservationCopy = (typeof reservationCopy)[ReservationLanguage];

export function getReservationCopy(lang: ReservationLanguage) {
  return reservationCopy[lang];
}
